using System;
using System.Collections.Generic;
using FenBrowser.Core.Dom.V2;
using FenBrowser.Core.Css;
using FenBrowser.FenEngine.Layout;
using SkiaSharp;

namespace FenBrowser.FenEngine.Layout.Tree
{
    /// <summary>
    /// Abstract base class for all nodes in the Layout Tree.
    /// Acts as the bridge between DOM+Style and Geometry.
    /// </summary>
    public abstract class LayoutBox
    {
        public readonly int StoreId;
        public readonly LayoutBoxStore Store;
        private readonly int _storeGeneration;
        private IList<LayoutBox> _children;

        /// <summary>
        /// Attempts to link this box back to a source DOM Node.
        /// Can be null for anonymous boxes.
        /// </summary>
        public Node SourceNode
        {
            get
            {
                EnsureAlive();
                return Store.GetSourceNode(StoreId);
            }
        }

        /// <summary>
        /// The Computed Style for this box.
        /// For anonymous boxes, this may be inherited or synthesized.
        /// </summary>
        public CssComputed ComputedStyle
        {
            get
            {
                EnsureAlive();
                return Store.GetStyle(StoreId);
            }
            set
            {
                EnsureAlive();
                Store.SetStyle(StoreId, value);
            }
        }

        /// <summary>
        /// Parent in the layout tree.
        /// </summary>
        public LayoutBox Parent
        {
            get
            {
                EnsureAlive();
                var parentId = Store.GetParentId(StoreId);
                return parentId >= 0 ? Store.GetWrapper(parentId) : null;
            }
            set
            {
                EnsureAlive();
                if (value != null)
                {
                    value.EnsureAlive();
                    EnsureSameStore(value);
                }
                Store.SetParent(StoreId, value?.StoreId ?? -1);
            }
        }

        /// <summary>
        /// Children boxes. The returned mutable view remains bound to this box's
        /// store generation; retaining it across LayoutBoxStore.Reset() cannot mutate
        /// a later tree that happens to reuse the same integer store id.
        /// </summary>
        public IList<LayoutBox> Children
        {
            get
            {
                EnsureAlive();
                return _children ??= new GenerationValidatedChildrenList(
                    this,
                    Store.GetChildrenList(StoreId));
            }
        }

        /// <summary>
        /// The computed geometry (margin/border/padding/content) for this box.
        /// Populated during the Layout phase.
        /// </summary>
        public BoxModel Geometry
        {
            get
            {
                EnsureAlive();
                return Store.GetGeometry(StoreId);
            }
            set
            {
                EnsureAlive();
                Store.SetGeometry(StoreId, value);
            }
        }

        /// <summary>
        /// If true, this box was generated by the layout engine and has no direct DOM counterpart.
        /// </summary>
        public bool IsAnonymous
        {
            get
            {
                EnsureAlive();
                return Store.GetIsAnonymous(StoreId);
            }
        }

        /// <summary>
        /// Static position of an out-of-flow box relative to its parent's content
        /// origin, captured during flow layout. Null when the formatting context
        /// did not record one. Valid for one layout pass only.
        /// </summary>
        public SKPoint? OutOfFlowStaticPosition;

        /// <summary>
        /// Returns true if the element is out of normal flow (absolute or fixed).
        /// </summary>
        public bool IsOutOfFlow
        {
            get
            {
                var pos = LayoutStyleResolver.GetEffectivePosition(ComputedStyle);
                if (string.IsNullOrEmpty(pos)) return false;
                return pos == "absolute" || pos == "fixed";
            }
        }

        protected LayoutBox(LayoutBoxStore store, int storeId)
        {
            Store = store ?? throw new ArgumentNullException(nameof(store));
            StoreId = storeId;
            _storeGeneration = store.Generation;
        }

        public void AddChild(LayoutBox child)
        {
            EnsureAlive();
            if (child == null) return;
            child.EnsureAlive();
            EnsureSameStore(child);
            Store.AddChild(StoreId, child.StoreId);
        }

        public override string ToString()
        {
            EnsureAlive();
            var source = SourceNode;
            var tag = source is Element e ? e.TagName : (source?.GetType().Name ?? "Anonymous");
            var type = GetType().Name;
            return $"{type} [{tag}]";
        }

        private void EnsureSameStore(LayoutBox other)
        {
            if (!ReferenceEquals(Store, other.Store))
            {
                throw new InvalidOperationException(
                    "Layout boxes from different LayoutBoxStore instances cannot share a parent/child relationship.");
            }
        }

        private void EnsureAlive()
        {
            Store.ValidateAccess(StoreId, _storeGeneration);
        }

        private sealed class GenerationValidatedChildrenList : IList<LayoutBox>
        {
            private readonly LayoutBox _owner;
            private readonly IList<LayoutBox> _inner;

            public GenerationValidatedChildrenList(LayoutBox owner, IList<LayoutBox> inner)
            {
                _owner = owner ?? throw new ArgumentNullException(nameof(owner));
                _inner = inner ?? throw new ArgumentNullException(nameof(inner));
            }

            public LayoutBox this[int index]
            {
                get
                {
                    EnsureOwnerAlive();
                    return _inner[index];
                }
                set
                {
                    EnsureOwnerAlive();
                    EnsureItemAlive(value);
                    _inner[index] = value;
                }
            }

            public int Count
            {
                get
                {
                    EnsureOwnerAlive();
                    return _inner.Count;
                }
            }

            public bool IsReadOnly
            {
                get
                {
                    EnsureOwnerAlive();
                    return _inner.IsReadOnly;
                }
            }

            public void Add(LayoutBox item)
            {
                EnsureOwnerAlive();
                EnsureItemAlive(item);
                _inner.Add(item);
            }

            public void Clear()
            {
                EnsureOwnerAlive();
                _inner.Clear();
            }

            public bool Contains(LayoutBox item)
            {
                EnsureOwnerAlive();
                EnsureItemAlive(item);
                return _inner.Contains(item);
            }

            public void CopyTo(LayoutBox[] array, int arrayIndex)
            {
                EnsureOwnerAlive();
                _inner.CopyTo(array, arrayIndex);
            }

            public IEnumerator<LayoutBox> GetEnumerator()
            {
                EnsureOwnerAlive();
                for (var i = 0; ; i++)
                {
                    EnsureOwnerAlive();
                    if (i >= _inner.Count)
                    {
                        yield break;
                    }

                    yield return _inner[i];
                }
            }

            System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

            public int IndexOf(LayoutBox item)
            {
                EnsureOwnerAlive();
                EnsureItemAlive(item);
                return _inner.IndexOf(item);
            }

            public void Insert(int index, LayoutBox item)
            {
                EnsureOwnerAlive();
                EnsureItemAlive(item);
                _inner.Insert(index, item);
            }

            public bool Remove(LayoutBox item)
            {
                EnsureOwnerAlive();
                EnsureItemAlive(item);
                return _inner.Remove(item);
            }

            public void RemoveAt(int index)
            {
                EnsureOwnerAlive();
                _inner.RemoveAt(index);
            }

            private void EnsureOwnerAlive() => _owner.EnsureAlive();

            private void EnsureItemAlive(LayoutBox item)
            {
                if (item == null)
                {
                    throw new ArgumentNullException(nameof(item));
                }

                item.EnsureAlive();
                _owner.EnsureSameStore(item);
            }
        }
    }
}
