using System.Collections.Generic;
using FenBrowser.Core.Dom.V2;
using FenBrowser.Core.Css;
using FenBrowser.FenEngine.Layout;

namespace FenBrowser.FenEngine.Layout.Tree
{
    /// <summary>
    /// Abstract base class for all nodes in the Layout Tree.
    /// Acts as the bridge between DOM+Style and Geometry.
    /// </summary>
    public abstract class LayoutBox
    {
        /// <summary>
        /// Attempts to link this box back to a source DOM Node.
        /// Can be null for anonymous boxes.
        /// </summary>
        public Node SourceNode { get; }

        /// <summary>
        /// The Computed Style for this box.
        /// For anonymous boxes, this may be inherited or synthesized.
        /// </summary>
        public CssComputed ComputedStyle { get; set; }

        /// <summary>
        /// Parent in the layout tree.
        /// </summary>
        public LayoutBox Parent { get; set; }

        /// <summary>
        /// Children boxes.
        /// </summary>
        public List<LayoutBox> Children { get; } = new List<LayoutBox>();

        /// <summary>
        /// The computed geometry (margin/border/padding/content) for this box.
        /// Populated during the Layout phase.
        /// </summary>
        public BoxModel Geometry { get; set; } = new BoxModel();
        
        /// <summary>
        /// If true, this box was generated by the layout engine and has no direct DOM counterpart.
        /// </summary>
        public bool IsAnonymous => SourceNode == null;

        /// <summary>
        /// Returns true if the element is out of normal flow (absolute or fixed).
        /// </summary>
        public bool IsOutOfFlow 
        {
            get
            {
                var pos = LayoutStyleResolver.GetEffectivePosition(ComputedStyle);
                if (string.IsNullOrEmpty(pos)) return false;
                return pos == "absolute" || pos == "fixed";
            }
        }

        protected LayoutBox(Node sourceNode, CssComputed style)
        {
            SourceNode = sourceNode;
            ComputedStyle = style;
        }

        public void AddChild(LayoutBox child)
        {
            if (child == null) return;
            child.Parent = this;
            Children.Add(child);
        }

        public override string ToString()
        {
            var tag = SourceNode is Element e ? e.TagName : (SourceNode?.GetType().Name ?? "Anonymous");
            var type = GetType().Name;
            return $"{type} [{tag}]";
        }
    }
}


