using System.Collections.Generic;
using FenBrowser.Core.Dom.V2;
using FenBrowser.Core.Css;
using FenBrowser.FenEngine.Layout;

namespace FenBrowser.FenEngine.Layout.Tree
{
    /// <summary>
    /// Abstract base class for all nodes in the Layout Tree.
    /// Acts as the bridge between DOM+Style and Geometry.
    /// </summary>
    public abstract class LayoutBox
    {
        public readonly int StoreId;
        public readonly LayoutBoxStore Store;
        private readonly int _storeGeneration;
        private IList<LayoutBox> _children;

        /// <summary>
        /// Attempts to link this box back to a source DOM Node.
        /// Can be null for anonymous boxes.
        /// </summary>
        public Node SourceNode
        {
            get
            {
                EnsureAlive();
                return Store.GetSourceNode(StoreId);
            }
        }

        /// <summary>
        /// The Computed Style for this box.
        /// For anonymous boxes, this may be inherited or synthesized.
        /// </summary>
        public CssComputed ComputedStyle 
        { 
            get
            {
                EnsureAlive();
                return Store.GetStyle(StoreId);
            }
            set
            {
                EnsureAlive();
                Store.SetStyle(StoreId, value);
            }
        }

        /// <summary>
        /// Parent in the layout tree.
        /// </summary>
        public LayoutBox Parent 
        { 
            get
            {
                EnsureAlive();
                return Store.GetParentId(StoreId) >= 0 ? Store.GetWrapper(Store.GetParentId(StoreId)) : null;
            }
            set
            {
                EnsureAlive();
                Store.SetParent(StoreId, value?.StoreId ?? -1);
            }
        }

        /// <summary>
        /// Children boxes.
        /// </summary>
        public IList<LayoutBox> Children
        {
            get
            {
                EnsureAlive();
                return _children ??= Store.GetChildrenList(StoreId);
            }
        }

        /// <summary>
        /// The computed geometry (margin/border/padding/content) for this box.
        /// Populated during the Layout phase.
        /// </summary>
        public BoxModel Geometry 
        { 
            get
            {
                EnsureAlive();
                return Store.GetGeometry(StoreId);
            }
            set
            {
                EnsureAlive();
                Store.SetGeometry(StoreId, value);
            }
        }
        
        /// <summary>
        /// If true, this box was generated by the layout engine and has no direct DOM counterpart.
        /// </summary>
        public bool IsAnonymous
        {
            get
            {
                EnsureAlive();
                return Store.GetIsAnonymous(StoreId);
            }
        }

        /// <summary>
        /// Returns true if the element is out of normal flow (absolute or fixed).
        /// </summary>
        public bool IsOutOfFlow 
        {
            get
            {
                var pos = LayoutStyleResolver.GetEffectivePosition(ComputedStyle);
                if (string.IsNullOrEmpty(pos)) return false;
                return pos == "absolute" || pos == "fixed";
            }
        }

        protected LayoutBox(LayoutBoxStore store, int storeId)
        {
            Store = store;
            StoreId = storeId;
            _storeGeneration = store?.Generation ?? 0;
        }

        public void AddChild(LayoutBox child)
        {
            EnsureAlive();
            if (child == null) return;
            Store.AddChild(StoreId, child.StoreId);
        }

        public override string ToString()
        {
            EnsureAlive();
            var tag = SourceNode is Element e ? e.TagName : (SourceNode?.GetType().Name ?? "Anonymous");
            var type = GetType().Name;
            return $"{type} [{tag}]";
        }

        private void EnsureAlive()
        {
            Store.ValidateAccess(StoreId, _storeGeneration);
        }
    }
}


