"""Generates FenBrowser.Core/Parsing/HtmlNamedCharacterReferences.cs from Python's copy of
the HTML named character references table (html.entities.html5: 2231 names, 106 of them the
legacy ones that need no semicolon). Run from the repo root."""
import html.entities

OUT = "FenBrowser.Core/Parsing/HtmlNamedCharacterReferences.cs"


def cs_literal(value: str) -> str:
    units = value.encode("utf-16-le")
    out = []
    for i in range(0, len(units), 2):
        out.append("\\u%04X" % int.from_bytes(units[i:i + 2], "little"))
    return '"' + "".join(out) + '"'


def main():
    table = html.entities.html5
    names = sorted(table)
    lines = []
    lines.append("// <auto-generated>")
    lines.append("// Generated by scripts/gen_html_entities.py from the HTML named character references")
    lines.append("// table (https://html.spec.whatwg.org/entities.json, as shipped in Python's html.entities).")
    lines.append("// Do not edit by hand.")
    lines.append("// </auto-generated>")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append("namespace FenBrowser.Core.Parsing")
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// HTML §13.5 named character references: every name (with its trailing semicolon")
    lines.append("    /// where the table has one) and the code points it stands for. The 106 legacy names")
    lines.append("    /// without a semicolon are the ones a reference may omit it for.")
    lines.append("    /// </summary>")
    lines.append("    public static class HtmlNamedCharacterReferences")
    lines.append("    {")
    lines.append("        /// <summary>The longest name in the table.</summary>")
    lines.append(f"        public const int MaxNameLength = {max(len(n) for n in names)};")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// HTML §13.2.5.73 (named character reference state): matches the longest name")
    lines.append("        /// that starts at <paramref name=\"position\"/> (just after the ampersand). Returns")
    lines.append("        /// false when no name matches.")
    lines.append("        /// </summary>")
    lines.append("        public static bool TryMatchLongest(string input, int position, out string replacement, out int length)")
    lines.append("        {")
    lines.append("            replacement = null;")
    lines.append("            length = 0;")
    lines.append("            if (input == null || position < 0 || position >= input.Length)")
    lines.append("                return false;")
    lines.append("            int max = Math.Min(MaxNameLength, input.Length - position);")
    lines.append("            for (int candidate = max; candidate > 0; candidate--)")
    lines.append("            {")
    lines.append("                if (s_table.TryGetValue(input.Substring(position, candidate), out var value))")
    lines.append("                {")
    lines.append("                    replacement = value;")
    lines.append("                    length = candidate;")
    lines.append("                    return true;")
    lines.append("                }")
    lines.append("            }")
    lines.append("")
    lines.append("            return false;")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>Looks a name up exactly (the name includes its semicolon when it has one).</summary>")
    lines.append("        public static bool TryGet(string name, out string replacement) => s_table.TryGetValue(name, out replacement);")
    lines.append("")
    lines.append("        public static int Count => s_table.Count;")
    lines.append("")
    lines.append("        private static readonly Dictionary<string, string> s_table = new(StringComparer.Ordinal)")
    lines.append("        {")
    for name in names:
        lines.append(f"            [\"{name}\"] = {cs_literal(table[name])},")
    lines.append("        };")
    lines.append("    }")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(names)} names")


if __name__ == "__main__":
    main()
