#!/usr/bin/env python3
"""Generate the media test fixtures in test_assets/media.

Every file is encoded from ffmpeg's synthetic sources (sine tones, test patterns),
so the fixtures carry no third-party content. Run from the repo root:

    python scripts/media/gen_fixtures.py            # regenerate everything
    python scripts/media/gen_fixtures.py --references   # regenerate only the decoded references
    python scripts/media/gen_fixtures.py --check    # verify files match the manifest

The manifest (test_assets/media/manifest.json) records, per file, the facts ffprobe
reports and the hand-checked result the WHATWG MIME Sniffing audio/video algorithm
must give. Tests read the manifest; they never shell out to ffmpeg.

Encoders differ between ffmpeg builds, so regenerated bytes (and hashes) can change.
Commit the regenerated files and manifest together.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

OUT_DIR = Path("test_assets/media")
MANIFEST = OUT_DIR / "manifest.json"

BITEXACT = ["-fflags", "+bitexact", "-flags:v", "+bitexact", "-flags:a", "+bitexact", "-map_metadata", "-1"]
SINE = ["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=1"]
SINE_44K = ["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=44100:duration=1"]
SINE_22K = ["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=22050:duration=1"]
PATTERN = ["-f", "lavfi", "-i", "testsrc2=size=64x48:rate=10:duration=1"]
VIDEO_ONE_THREAD = ["-threads", "1"]

# name, ffmpeg arguments (inputs + codec options), expected sniff result, notes.
# The sniff expectation is worked out by hand from the WHATWG rules, not by running our code.
FIXTURES: list[tuple[str, list[str], str | None, str]] = [
    ("sine_mp3_noid3.mp3", SINE_44K + ["-c:a", "libmp3lame", "-b:a", "128k", "-id3v2_version", "0", "-write_xing", "0"],
     "audio/mpeg", "MPEG-1 Layer III frames from byte 0: the MP3-without-ID3 signature"),
    ("sine_mp3_id3.mp3", SINE_44K + ["-c:a", "libmp3lame", "-b:a", "128k", "-id3v2_version", "4"],
     "audio/mpeg", "ID3v2 tag: the ID3 pattern row"),
    ("sine_mp3_mpeg2.mp3", SINE_22K + ["-c:a", "libmp3lame", "-b:a", "64k", "-id3v2_version", "0", "-write_xing", "0"],
     "audio/mpeg", "MPEG-2 Layer III: half-rate tables and the 72 scale"),
    ("sine_opus.ogg", SINE + ["-c:a", "libopus", "-b:a", "32k"],
     "application/ogg", "OggS NUL pattern row"),
    ("sine_vorbis.ogg", SINE + ["-c:a", "libvorbis", "-q:a", "0"],
     "application/ogg", "OggS NUL pattern row"),
    ("sine_flac.flac", SINE + ["-c:a", "flac"],
     None, "fLaC is not in the sniffing table"),
    ("sine_pcm16.wav", SINE + ["-c:a", "pcm_s16le"],
     "audio/wave", "RIFF WAVE pattern row"),
    ("sine_aac.m4a", SINE + ["-c:a", "aac", "-b:a", "64k"],
     None, "ftyp M4A with no brand starting mp4"),
    ("sine_aac.aac", SINE + ["-c:a", "aac", "-b:a", "64k", "-f", "adts"],
     None, "ADTS frames: no signature in the sniffing table"),
    ("sine_opus.webm", SINE + ["-c:a", "libopus", "-b:a", "32k"],
     "video/webm", "EBML DocType webm (audio-only WebM still sniffs as video/webm)"),
    ("pattern_vp9.webm", PATTERN + VIDEO_ONE_THREAD + ["-c:v", "libvpx-vp9", "-b:v", "50k", "-deadline", "good", "-cpu-used", "4"],
     "video/webm", "EBML DocType webm"),
    ("pattern_vp8_vorbis.webm", PATTERN + SINE + VIDEO_ONE_THREAD + ["-c:v", "libvpx", "-b:v", "50k", "-c:a", "libvorbis", "-q:a", "0", "-shortest"],
     "video/webm", "EBML DocType webm, two tracks"),
    ("pattern_av1.webm", PATTERN + VIDEO_ONE_THREAD + ["-c:v", "libaom-av1", "-b:v", "50k", "-cpu-used", "8", "-row-mt", "0"],
     "video/webm", "EBML DocType webm"),
    ("pattern_vp9.mkv", PATTERN + VIDEO_ONE_THREAD + ["-c:v", "libvpx-vp9", "-b:v", "50k", "-deadline", "good", "-cpu-used", "4"],
     None, "EBML DocType matroska is not webm"),
    ("pattern_h264_aac.mp4", PATTERN + SINE + VIDEO_ONE_THREAD + ["-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "64k", "-shortest"],
     "video/mp4", "ftyp isom with compatible brand mp41"),
    ("pattern_h264_faststart.mp4", PATTERN + VIDEO_ONE_THREAD + ["-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-movflags", "+faststart"],
     "video/mp4", "moov before mdat"),
    ("pattern_h264_fragmented.mp4", PATTERN + VIDEO_ONE_THREAD + ["-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-movflags", "frag_keyframe+empty_moov+default_base_moof"],
     "video/mp4", "fragmented MP4 (MSE shape): 28-byte ftyp iso5, compatible mp41 at offset 24"),
]


# Decoded references: ffmpeg's own decode of a fixture, for decoders that are not bit-exact
# with libavcodec (the OS H.264 decoder differs by rounding; tests compare by PSNR).
# name, source fixture, ffmpeg output arguments, note.
REFERENCES: list[tuple[str, str, list[str], str]] = [
    ("pattern_h264_ref.nv12", "pattern_h264_aac.mp4", ["-map", "0:v:0", "-f", "rawvideo", "-pix_fmt", "nv12"],
     "ffmpeg's decode of the H.264 track, 10 NV12 pictures of 64x48"),
]


def run(cmd: list[str]) -> str:
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return result.stdout


def probe(path: Path) -> dict:
    data = json.loads(run([
        "ffprobe", "-v", "error", "-print_format", "json",
        "-show_entries",
        "format=format_name,duration:stream=index,codec_type,codec_name,width,height,sample_rate,channels,time_base",
        str(path),
    ]))
    streams = []
    for s in data.get("streams", []):
        entry = {"index": s["index"], "type": s["codec_type"], "codec": s["codec_name"], "timeBase": s.get("time_base")}
        if s["codec_type"] == "video":
            entry["width"] = s.get("width")
            entry["height"] = s.get("height")
        elif s["codec_type"] == "audio":
            entry["sampleRate"] = int(s.get("sample_rate", 0))
            entry["channels"] = s.get("channels")
        streams.append(entry)
    fmt = data.get("format", {})
    return {
        "container": fmt.get("format_name"),
        "durationSeconds": round(float(fmt["duration"]), 3) if "duration" in fmt else None,
        "streams": streams,
    }


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def ffmpeg_version() -> str:
    return run(["ffmpeg", "-version"]).splitlines()[0]


def generate() -> int:
    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            print(f"{tool} is not on PATH", file=sys.stderr)
            return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for name, args, sniff, note in FIXTURES:
        path = OUT_DIR / name
        run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", *args, *BITEXACT, str(path)])
        entries.append({
            "file": name,
            "bytes": path.stat().st_size,
            "sha256": sha256(path),
            "sniff": sniff,
            "note": note,
            **probe(path),
        })
        print(f"{name:32} {path.stat().st_size:7} bytes  sniff={sniff}")

    manifest = {
        "generator": "scripts/media/gen_fixtures.py",
        "ffmpeg": ffmpeg_version(),
        "fixtures": entries,
        "references": references(),
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    return 0


def references() -> list[dict]:
    entries = []
    for name, source, args, note in REFERENCES:
        path = OUT_DIR / name
        run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(OUT_DIR / source), *args, str(path)])
        entries.append({"file": name, "source": source, "bytes": path.stat().st_size, "sha256": sha256(path), "note": note})
        print(f"{name:32} {path.stat().st_size:7} bytes  from {source}")
    return entries


def regenerate_references() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    manifest["references"] = references()
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    return 0


def check() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    bad = 0
    for entry in manifest["fixtures"] + manifest.get("references", []):
        path = OUT_DIR / entry["file"]
        if not path.exists():
            print(f"missing: {entry['file']}")
            bad += 1
        elif sha256(path) != entry["sha256"]:
            print(f"changed: {entry['file']}")
            bad += 1
    print("ok" if bad == 0 else f"{bad} problem(s)")
    return 1 if bad else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify files against the manifest instead of regenerating")
    parser.add_argument("--references", action="store_true", help="regenerate only the decoded references")
    args = parser.parse_args()
    if args.check:
        return check()
    if args.references:
        return regenerate_references()
    return generate()


if __name__ == "__main__":
    sys.exit(main())
