#!/usr/bin/env python
"""Regenerate docs/test262_results.md from the local batched result store.

Source of truth (local, gitignored): Results/test262/batched/b_*.json
Committed, followable output:        docs/test262_results.md

Workflow: fix a category -> re-run ONLY that category into its b_*.json
(python scripts/test262/run.py category <path>) -> run this -> commit the .md.
Never re-run the full suite just to refresh numbers.
"""
import json, glob, collections, os, datetime

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

BATCHED = "Results/test262/batched"
DOC = "docs/test262_results.md"


def keyfor(path):
    p = path.replace("\\", "/").split("/")
    if len(p) < 3:
        return "/".join(p)
    a = p[1]
    if a == "built-ins":
        return f"built-ins/{p[2]}"
    if a == "intl402":
        return f"intl402/{p[2]}" if len(p) > 3 else "intl402"
    if a == "language":
        return "language/" + "/".join(p[2:4]) if len(p) > 3 else f"language/{p[2]}"
    return a


def main():
    latest = {}
    dupes = collections.Counter()
    revisions = collections.Counter()
    for f in glob.glob(BATCHED + "/b_*.json"):
        mtime = os.path.getmtime(f)
        try:
            d = json.load(open(f, encoding="utf-8-sig"))
        except Exception:
            continue
        rev = d.get("fenbrowserCommit") or "unknown"
        revisions[rev[:12] + ("-dirty" if rev.endswith("-dirty") else "")] += 1
        for t in d.get("tests", []):
            p = t.get("path", "")
            if not p or "_FIXTURE" in p:
                continue
            if "_dstr_tmp/expressions_" in p:
                p = "test/language/expressions/class/dstr/" + os.path.basename(p)
            elif "_dstr_tmp/statements_" in p:
                p = "test/language/statements/class/dstr/" + os.path.basename(p)
            if p in latest:
                dupes[p] += 1
                if mtime <= latest[p][0]:
                    continue
            latest[p] = (mtime, t)

    cat = collections.defaultdict(collections.Counter)
    for _, t in latest.values():
        p = t.get("path", "")
        if "_dstr_tmp/expressions_" in p:
            p = "test/language/expressions/class/dstr/" + os.path.basename(p)
        elif "_dstr_tmp/statements_" in p:
            p = "test/language/statements/class/dstr/" + os.path.basename(p)
        k = keyfor(p)
        st = (t.get("status") or "").lower()
        cat[k]["total"] += 1
        if st in ("pass", "passed", "ok"):
            cat[k]["pass"] += 1
        elif st in ("harnessunsupported", "invalidtestconfiguration", "unsupportedfeature"):
            cat[k]["notrun"] += 1
        elif st == "timedout":
            cat[k]["timeout"] += 1

    if dupes:
        print(f"WARNING: {len(dupes)} duplicate test path(s) found across batches; newest result kept:")
        for p in list(dupes)[:10]:
            print(f"  {p}")

    rows = []
    for k, c in cat.items():
        tot, pa = c["total"], c["pass"]
        rows.append((k, tot, pa, tot - pa, round(100.0 * pa / tot, 1) if tot else 0.0))
    T = sum(r[1] for r in rows)
    P = sum(r[2] for r in rows)
    NOTRUN = sum(c["notrun"] for c in cat.values())
    TIMEOUTS = sum(c["timeout"] for c in cat.values())
    below = sorted([r for r in rows if r[4] < 100.0], key=lambda r: -r[3])
    perfect = [r for r in rows if r[4] >= 100.0]

    ts = datetime.date.today().isoformat()
    out = []
    out.append("# Test262 — Real Results (per category)\n")
    out.append("> Generated by `scripts/test262/report.py` from the local batched run store. "
               "**This file is the source of truth — read it instead of re-running the full suite.** "
               "See the test262 results rule in AGENTS.md / CLAUDE.md.\n")
    out.append(f"- Snapshot: **{ts}**")
    out.append(f"- Overall: **{P}/{T} = {round(100*P/T,2) if T else 0}%**")
    out.append(f"- Not run (unsupported harness/feature/config): **{NOTRUN}**; timed out: **{TIMEOUTS}**")
    # Every batch records the engine revision it ran; a store built across
    # several revisions is a mix, and says so.
    rev_text = ", ".join(f"`{r}` ({n} batches)" for r, n in revisions.most_common())
    out.append(f"- Engine revisions: {rev_text}" + (" — **mixed: rerun stale batches**" if len(revisions) > 1 else ""))
    out.append(f"- Categories: **{len(rows)}** total, **{len(perfect)}** at 100%, "
               f"**{len(below)}** below 100% (the worklist)\n")
    out.append("## Below 100% — worklist (ranked by failures, biggest wins first)\n")
    out.append("| # | Category | Total | Pass | Fail | Pass% |")
    out.append("|--:|----------|------:|-----:|-----:|------:|")
    for i, (k, tot, pa, fa, pct) in enumerate(below, 1):
        out.append(f"| {i} | `{k}` | {tot} | {pa} | {fa} | {pct}% |")
    out.append("")
    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {DOC}: {P}/{T} ({round(100*P/T,2) if T else 0}%), "
          f"{len(below)} categories below 100%, {NOTRUN} not run, {TIMEOUTS} timed out")
    if len(revisions) > 1:
        print(f"WARNING: results come from {len(revisions)} engine revisions: {rev_text}")


if __name__ == "__main__":
    main()
